-- [9.06.00.000.03] [20230517] [PTRAMBAKE] [START]
DELETE FROM NOTIFICATION_MODULES WHERE NOTIFICATION_BRAND_NAME='LOGIN_CONFIG' AND NOTIFICATION_MODULE_ID IN ('WRHS-STAGE','REPR-STAGE','ERR-STAGE','DUPL-STAGE','CRT-STAGE','AUTH-STAGE','WRHS_PYMT','WRHS_MSG','UMTCH-STAGE','PYMT-TYPE','MTCH-STAGE','MSG-TYPE','CRT_PYMT','CRT_MSG','CANC_PYMT','CANC_MSG','ACK-STAGE','HV-STAGE');

Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','WRHS_PYMT','Payments sent to Scheduled stage','Notification when payments sent to Scheduled stage');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','WRHS_MSG','Messages sent to Scheduled stage','Notification when messages sent to Scheduled stage');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','UMTCH-STAGE','Payment rejection received','Notification when a rejection for a payment is received ');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','PYMT-TYPE','Payments type','Notification when a payments sent to Error,Duplicate,Repair,Authorise stage');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','MTCH-STAGE','Rejection of payment','Notification when a payment is rejected');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','MSG-TYPE','Messages type','Notification when a messages sent to Error,Duplicate,Repair,Authorise stage');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','CRT_PYMT','Payments initiatiated','Notification when payments are initiated');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','CRT_MSG','Messages initiated','Notification when messages are initiated');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','CANC_PYMT','Cancelled payments','Notification when payments are cancelled');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','CANC_MSG','Cancelled messages','Notification when messages are cancelled');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','ACK-STAGE','Payment acknowledgements received','Notification when acknowledgements for payments are received');
Insert into NOTIFICATION_MODULES (NOTIFICATION_BRAND_NAME,NOTIFICATION_MODULE_ID,NOTIFICATION_MODULE_NAME,NOTIFICATION_MODULE_DESC) values ('LOGIN_CONFIG','HV-STAGE','High value payments','Notification when a high value payment is processed');

-- [9.06.00.000.03] [20230517] [PTRAMBAKE] [END]

COMMIT;
EXIT;